interfaces:
 - name: Ethernet0/0
   description: Link to D1 configured by Ansible
   mode: trunk
   allowed_vlans: 10-21,40
   native: 10
   encap: dot1q

 - name: Ethernet0/1
   description: Link to D1 configured by Ansible
   mode: trunk
   allowed_vlans: 10-21,40
   native: 10
   encap: dot1q

 - name: Ethernet0/2
   description: Link to D1 configured by Ansible
   mode: trunk
   allowed_vlans: 10-21,40
   native: 10
   encap: dot1q 

 - name: Ethernet0/3
   description: Link to D1 configured by Ansible
   mode: trunk
   allowed_vlans: 10-21,40
   native: 10
   encap: dot1q

 - name: Ethernet1/0
   description: Link to A1 configured by Ansible
   mode: trunk
   allowed_vlans: 10-21,40
   native: 10
   encap: dot1q

 - name: Ethernet1/1
   description: Link to A1 configured by Ansible
   mode: trunk
   allowed_vlans: 10-21,40
   native: 10
   encap: dot1q

 - name: Loopback 0
   description: Loopback 0 configured by Ansible
   ipv4: '192.168.1.1/24'
   ipv6: "2001:DB8:ACAD:1000::1/64"
   link_local: FE80::D2:3
   mode: L3

 - name: Loopback 1
   description: Loopback 1 configured by Ansible
   ipv4: '209.165.200.225/27'
   ipv6: "2001:DB8:ACAD:200::225/64"
   link_local: FE80::D2:4
   mode: L3
   

 - name: Vlan 11
   description: int VLAN 11 configured by Ansible
   ipv4: 10.11.0.2/24
   ipv6: "2001:DB8:ACAD:11::2/64"
   link_local: FE80::D2:1
   mode: L3
   hsrpid: 11
   vip: 10.11.0.254
   hello: 250 
   dead: 750 
   priority: 100
   preempt: preempt 
   auth: md5
   string: Super53cret


 - name: Vlan 21
   description: int VLAN 21 configured by Ansible
   ipv4: 10.21.0.2/24
   ipv6: "2001:DB8:ACAD:21::2/64"
   link_local: FE80::D2:2
   mode: L3
   hsrpid: 21
   vip: 10.21.0.254
   hello: 250 
   dead: 750
   priority: 150
   preempt: preempt 
   auth: md5
   string: Super53cret
   trackid: 4
   trackintf: Loopback 0

portchannels:
  - id: 1
    members:
     - member: Ethernet0/0
       mode: active
     - member: Ethernet0/1
       mode: active
     - member: Ethernet0/2
       mode: active
     - member: Ethernet0/3
       mode: active
    allowed_vlans: 10-21,40
    native: 10
  - id: 2
    members:
      - member: Ethernet1/0
        mode: active
      - member: Ethernet1/1
        mode: active
      - member: Ethernet1/2
        mode: active
    allowed_vlans: 10-21,40
    native: 10

