---
# tasks file for loopback

  - name: Create loopbacks 
    cisco.ios.ios_interfaces:
      config:
        - name: "{{ item.name }}" 
          enabled: true
          description: '"{{ item.name }}" created by Ansible'
      state: merged
    loop: "{{ interfaces }}"
    when: "'Loopback' in item.name"
    tags: intfcreate
 
  - name: Configure IPv4 loopback addresses
    cisco.ios.ios_config:
      lines:
      - ip address {{ item.ipv4 | ansible.utils.ipaddr('address') }} {{ item.ipv4 | ansible.utils.ipaddr('netmask') }}
      - no shut
      parents: interface {{ item.name }}
    loop: "{{ interfaces }}"
    loop_control:
      label: "{{ item.name }}"
    when: "'Loopback' in item.name or 'Vlan' in item.name  and 'A' not in inventory_hostname "   

  - name: Configure IPv6 loopback addresses
    cisco.ios.ios_config:
      lines:
      - ipv6 address {{ item.ipv6 | ansible.utils.ipaddr('host') }}
      parents: interface {{ item.name }}
    loop: "{{ interfaces }}"
    loop_control:
      label: "{{ item.name }}"
    when: "'Loopback' in item.name or 'Vlan' in item.name and 'A' not in inventory_hostname " 

  - name: Configure IPv6 loopback link-local addresses
    cisco.ios.ios_config:
      lines:
        - ipv6 address {{ item.link_local | ansible.utils.ipaddr('address') }} link-local
      parents: interface {{ item.name }}
    loop: "{{ interfaces }}"
    loop_control:
      label: "{{ item.name }}"
    when: item.link_local is defined
    tags: linklocal

  - name: Run show ip int brief
    cisco.ios.ios_command:
      commands: show ip interface brief
    register: myint

  - name: Display 'sh ip int brief' result
    debug:
      msg: "{{ myint }}" 