---
# tasks file for sw_interfaces
- name: Turn on interfaces
  ios_interfaces:
    config:
      - name: "{{ item.name }}"
        description: "{{ item.description }}"
        enabled: true
    state: merged
  loop: "{{ interfaces }}"
  tags: enableintf

- name: Configuring  trunk ports
  cisco.ios.ios_l2_interfaces:
    config:
      - name: "{{ item.name }}"
        mode: trunk
        trunk:
          allowed_vlans: "{{ item.allowed_vlans }}"
          native_vlan: "{{ item.native }}"
          # pruning_vlans: 10,20
          encapsulation: "{{ item.encap }}"
    state: merged
  loop: "{{ interfaces }}"
  when: "item.mode is defined and item.mode == 'trunk'"
  loop_control:
    label: "{{ item.name }}"
  tags: trunks

- name: Configuring  access ports
  cisco.ios.ios_l2_interfaces:
    config:
      - name: "{{ item.name }}"
        mode: access
        access:
          vlan: "{{ item.access_vlan }}"
        voice:
          vlan: "{{ item.voice_vlan }}"
    state: merged
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when: "item.mode is defined and item.mode == 'access'"
  tags: access
 

- name: Configure interface addresses
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ item.name }}"
        ipv4:
          - address: "{{ item.ipv4 }}"
        ipv6:
          - address: "{{ item.ipv6 }}"
    state: merged
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when: item.ipv4 is defined or item.ipv6 is defined
  # when: "item.mode is not defined"
  tags: addresses

- name: Configure IPv6 link-local addresses
  cisco.ios.ios_config:
    lines:
      - ipv6 address {{ item.link_local | ansible.netcommon.ipaddr('address') }} link-local
    parents: interface {{ item.name }}
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when: 
    - item.link_local is defined
    - item.mode == 'L3'
  tags: linklocal

